// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DPM_CER
Rcpp::List DPM_CER(const arma::imat& G_mat, const arma::ivec& G_0, const double a, const double b, const double c, const int sample, const int burn, const int thinning);
RcppExport SEXP _DPmCER_DPM_CER(SEXP G_matSEXP, SEXP G_0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type G_mat(G_matSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type G_0(G_0SEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type c(cSEXP);
    Rcpp::traits::input_parameter< const int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type thinning(thinningSEXP);
    rcpp_result_gen = Rcpp::wrap(DPM_CER(G_mat, G_0, a, b, c, sample, burn, thinning));
    return rcpp_result_gen;
END_RCPP
}
// distH
int distH(const arma::ivec& G_1, const arma::ivec& G_2);
RcppExport SEXP _DPmCER_distH(SEXP G_1SEXP, SEXP G_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type G_1(G_1SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type G_2(G_2SEXP);
    rcpp_result_gen = Rcpp::wrap(distH(G_1, G_2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_int_ker_basemeas_minus_max
double cpp_int_ker_basemeas_minus_max(const int N, const int d_bar, const double a, const double b, const double d);
RcppExport SEXP _DPmCER_cpp_int_ker_basemeas_minus_max(SEXP NSEXP, SEXP d_barSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type d_bar(d_barSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_int_ker_basemeas_minus_max(N, d_bar, a, b, d));
    return rcpp_result_gen;
END_RCPP
}
// sample_from_CER
arma::imat sample_from_CER(const arma::ivec& G, const double alpha, const int n);
RcppExport SEXP _DPmCER_sample_from_CER(SEXP GSEXP, SEXP alphaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_from_CER(G, alpha, n));
    return rcpp_result_gen;
END_RCPP
}
// log_lik_CER
double log_lik_CER(const arma::ivec& G, const arma::ivec& G_m, const double alpha);
RcppExport SEXP _DPmCER_log_lik_CER(SEXP GSEXP, SEXP G_mSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type G_m(G_mSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lik_CER(G, G_m, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DPmCER_DPM_CER", (DL_FUNC) &_DPmCER_DPM_CER, 8},
    {"_DPmCER_distH", (DL_FUNC) &_DPmCER_distH, 2},
    {"_DPmCER_cpp_int_ker_basemeas_minus_max", (DL_FUNC) &_DPmCER_cpp_int_ker_basemeas_minus_max, 5},
    {"_DPmCER_sample_from_CER", (DL_FUNC) &_DPmCER_sample_from_CER, 3},
    {"_DPmCER_log_lik_CER", (DL_FUNC) &_DPmCER_log_lik_CER, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DPmCER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
