# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DPM_CER <- function(G_mat, G_0, a, b, c, sample = 1000L, burn = 0L, thinning = 1L) {
    .Call(`_DPmCER_DPM_CER`, G_mat, G_0, a, b, c, sample, burn, thinning)
}

distH <- function(G_1, G_2) {
    .Call(`_DPmCER_distH`, G_1, G_2)
}

cpp_int_ker_basemeas_minus_max <- function(N, d_bar, a, b, d) {
    .Call(`_DPmCER_cpp_int_ker_basemeas_minus_max`, N, d_bar, a, b, d)
}

sample_from_CER <- function(G, alpha, n) {
    .Call(`_DPmCER_sample_from_CER`, G, alpha, n)
}

log_lik_CER <- function(G, G_m, alpha) {
    .Call(`_DPmCER_log_lik_CER`, G, G_m, alpha)
}

